- mark: ①
  name: 施工组织设计
  points:
  - id: ①-1
    name: 施工组织总体设计，方案针对性及施工段划分
    phrases:
    - 施工组织总体设计，方案针对性及施工段划分
    - 施工组织总体设计
    - 方案针对性
    - 施工段划分
    terms:
    - 施工
    - 组织
    - 总体设计
    - 方案
    - 针对性
    - 划分
  - id: ①-2
    name: 施工现场平面布置和临时设施、临时道路布置
    phrases:
    - 施工现场平面布置和临时设施、临时道路布置
    - 施工现场平面布置
    - 临时设施
    - 临时道路布置
    terms:
    - 施工现场
    - 平面布置
    - 临时
    - 设施
    - 道路
    - 布置
  - id: ①-3
    name: 施工进度计划和各阶段进度的保证措施
    phrases:
    - 施工进度计划和各阶段进度的保证措施
    - 施工进度计划
    - 各阶段进度的保证措施
    terms:
    - 施工进度
    - 阶段
    - 进度
    - 保证
    - 措施
  - id: ①-4
    name: 各分部分项工程的施工方案及质量保证措施
    phrases:
    - 各分部分项工程的施工方案及质量保证措施
    - 各分部分项工程的施工方案
    - 质量保证措施
    terms:
    - 各分
    - 部分
    - 施工
    - 方案
    - 质量保证
    - 措施
  - id: ①-5
    name: 安全文明施工及环境保护措施
    phrases:
    - 安全文明施工及环境保护措施
    - 安全文明施工
    - 环境保护措施
    terms:
    - 安全
    - 文明
    - 施工
    - 环境保护
    - 措施
  - id: ①-6
    name: 项目管理班子的人员配备、素质及管理经验
    phrases:
    - 项目管理班子的人员配备、素质及管理经验
    - 项目管理班子的人员配备
    - 素质
    - 管理经验
    terms:
    - 项目管理
    - 班子
    - 人员配备
    - 素质
    - 经验
  - id: ①-7
    name: 劳动力、机械设备和材料投入计划
    phrases:
    - 劳动力、机械设备和材料投入计划
    - 劳动力
    - 机械设备
    - 材料投入计划
    terms:
    - 劳动力
    - 机械设备
    - 材料
    - 投入
  - id: ①-8
    name: 关键施工技术、工艺及工程项目实施的重点、难点和解决方案
    phrases:
    - 关键施工技术、工艺及工程项目实施的重点、难点和解决方案
    - 关键施工技术
    - 工艺
    - 工程项目实施的重点
    - 难点
    - 解决方案
    terms:
    - 关键
    - 施工
    - 技术
    - 工艺
    - 工程项目
    - 实施
    - 重点
    - 难点
    - 解决方案
  - id: ①-9
    name: 冬雨季施工、已有设施、管线的加固、保护等特殊情况下的施工措施
    phrases:
    - 冬雨季施工、已有设施、管线的加固、保护等特殊情况下的施工措施
    - 冬雨季施工
    - 已有设施
    - 管线的加固
    - 保护等特殊情况下的施工措施
    terms:
    - 雨季
    - 施工
    - 已有
    - 设施
    - 管线
    - 加固
    - 保护
    - 特殊
    - 情况
    - 措施
  phrases:
  - 施工组织设计
  terms:
  - 施工
  - 组织
  - 设计
- mark: ②
  name: 质量管理体系与措施
  points:
  - id: ②-1
    name: 质量方针与目标体系
    phrases:
    - 质量方针与目标体系
    - 质量方针
    - 目标体系
    terms:
    - 质量方针
    - 目标
  - id: ②-2
    name: 组织机构与职责体系
    phrases:
    - 组织机构与职责体系
    - 组织机构
    - 职责体系
    terms:
    - 组织
    - 机构
    - 职责
  - id: ②-3
    name: 制度体系建设
    phrases:
    - 制度体系建设
    terms:
    - 制度
  - id: ②-4
    name: 施工组织设计质量策划
    phrases:
    - 施工组织设计质量策划
    terms:
    - 施工
    - 组织
    - 设计
    - 质量
    - 策划
  - id: ②-5
    name: 专项方案质量策划
    phrases:
    - 专项方案质量策划
    terms:
    - 专项
    - 方案
    - 质量
    - 策划
  - id: ②-6
    name: 质量验收策划
    phrases:
    - 质量验收策划
    terms:
    - 质量
    - 验收
    - 策划
  - id: ②-7
    name: 文件管理体系构建
    phrases:
    - 文件管理体系构建
    terms:
    - 文件
    - 管理体系
    - 构建
  phrases:
  - 质量管理体系与措施
  - 质量管理体系
  - 措施
  terms:
  - 质量
  - 管理体系
  - 措施
- mark: ②
  name: 质量管理体系与措施
  points:
  - id: ②-1
    name: 质量方针与目标体系
    phrases:
    - 质量方针与目标体系
    - 质量方针
    - 目标体系
    terms:
    - 质量方针
    - 目标
  - id: ②-2
    name: 组织机构与职责体系
    phrases:
    - 组织机构与职责体系
    - 组织机构
    - 职责体系
    terms:
    - 组织
    - 机构
    - 职责
  - id: ②-3
    name: 制度体系建设
    phrases:
    - 制度体系建设
    terms:
    - 制度
  - id: ②-4
    name: 施工组织设计质量策划
    phrases:
    - 施工组织设计质量策划
    terms:
    - 施工
    - 组织
    - 设计
    - 质量
    - 策划
  - id: ②-5
    name: 专项方案质量策划
    phrases:
    - 专项方案质量策划
    terms:
    - 专项
    - 方案
    - 质量
    - 策划
  - id: ②-6
    name: 质量验收策划
    phrases:
    - 质量验收策划
    terms:
    - 质量
    - 验收
    - 策划
  - id: ②-7
    name: 文件管理体系构建
    phrases:
    - 文件管理体系构建
    terms:
    - 文件
    - 管理体系
    - 构建
  - id: ②-8
    name: 追溯体系构建
    phrases:
    - 追溯体系构建
    terms:
    - 追溯
    - 构建
  - id: ②-9
    name: 质量分析与改进机制
    phrases:
    - 质量分析与改进机制
    - 质量分析
    - 改进机制
    terms:
    - 质量
    - 分析
    - 改进
    - 机制
  - id: ②-10
    name: 培训与提升体系
    phrases:
    - 培训与提升体系
    - 培训
    - 提升体系
    terms:
    - 培训
    - 提升
  - id: ②-11
    name: 原材料与构配件采购管控
    phrases:
    - 原材料与构配件采购管控
    - 原材料
    - 构配件采购管控
    terms:
    - 原材料
    - 构配件
    - 采购
    - 管控
  - id: ②-12
    name: 原材料与构配件进场检验
    phrases:
    - 原材料与构配件进场检验
    - 原材料
    - 构配件进场检验
    terms:
    - 原材料
    - 构配件
    - 进场
    - 检验
  - id: ②-13
    name: 原材料与构配件存储防护
    phrases:
    - 原材料与构配件存储防护
    - 原材料
    - 构配件存储防护
    terms:
    - 原材料
    - 构配件
    - 存储
    - 防护
  - id: ②-14
    name: 图纸会审
    phrases:
    - 图纸会审
    terms:
    - 图纸
    - 会审
  - id: ②-15
    name: 技术交底
    phrases:
    - 技术交底
    terms:
    - 技术
    - 交底
  - id: ②-16
    name: 设备与仪器管控
    phrases:
    - 设备与仪器管控
    - 设备
    - 仪器管控
    terms:
    - 设备
    - 仪器
    - 管控
  - id: ②-17
    name: 施工场地准备
    phrases:
    - 施工场地准备
    terms:
    - 施工
    - 场地
    - 准备
  - id: ②-18
    name: 施工工序质量控制
    phrases:
    - 施工工序质量控制
    terms:
    - 施工
    - 工序
    - 质量
    - 控制
  - id: ②-19
    name: 工序质量控制
    phrases:
    - 工序质量控制
    terms:
    - 工序
    - 质量
    - 控制
  - id: ②-20
    name: 测量放线控制
    phrases:
    - 测量放线控制
    terms:
    - 测量
    - 放线
    - 控制
  - id: ②-21
    name: 质量通病防治
    phrases:
    - 质量通病防治
    terms:
    - 质量
    - 通病
    - 防治
  - id: ②-22
    name: 重难点工程专项控制
    phrases:
    - 重难点工程专项控制
    terms:
    - 重难点
    - 专项
    - 控制
  - id: ②-23
    name: 检验批验收管控措施
    phrases:
    - 检验批验收管控措施
    terms:
    - 检验
    - 验收
    - 管控
    - 措施
  - id: ②-24
    name: 分部分项工程验收管控措施
    phrases:
    - 分部分项工程验收管控措施
    terms:
    - 部分
    - 工程验收
    - 管控
    - 措施
  - id: ②-25
    name: 隐蔽工程验收管控措施
    phrases:
    - 隐蔽工程验收管控措施
    terms:
    - 隐蔽
    - 工程验收
    - 管控
    - 措施
  - id: ②-26
    name: 单位工程验收管控措施
    phrases:
    - 单位工程验收管控措施
    terms:
    - 单位
    - 工程验收
    - 管控
    - 措施
  - id: ②-27
    name: 质量问题与事故处理措施
    phrases:
    - 质量问题与事故处理措施
    - 质量问题
    - 事故处理措施
    terms:
    - 质量
    - 问题
    - 事故
    - 处理
    - 措施
  - id: ②-28
    name: 成品保护质量管控措施
    phrases:
    - 成品保护质量管控措施
    terms:
    - 成品
    - 保护
    - 质量
    - 管控
    - 措施
  - id: ②-29
    name: 质量管理监督检查机制
    phrases:
    - 质量管理监督检查机制
    terms:
    - 质量
    - 监督
    - 检查
    - 机制
  - id: ②-30
    name: 质量管理考核奖惩机制
    phrases:
    - 质量管理考核奖惩机制
    terms:
    - 质量
    - 考核
    - 奖惩
    - 机制
  - id: ②-31
    name: 质量管理应急保障机制
    phrases:
    - 质量管理应急保障机制
    terms:
    - 质量
    - 应急
    - 保障机制
  phrases:
  - 质量管理体系与措施
  - 质量管理体系
  - 措施
  terms:
  - 质量
  - 管理体系
  - 措施
- mark: ③
  name: 安全管理体系与措施
  points:
  - id: ③-1
    name: 安全生产管理体系与组织机构健全
    phrases:
    - 安全生产管理体系与组织机构健全
    - 安全生产管理体系
    - 组织机构健全
    terms:
    - 安全
    - 生产
    - 管理体系
    - 组织
    - 机构
    - 健全
  - id: ③-2
    name: 按工程规模足额配置专职安全员，明确安全员岗位职责
    phrases:
    - 按工程规模足额配置专职安全员，明确安全员岗位职责
    - 按工程规模足额配置专职安全员
    - 明确安全员岗位职责
    terms:
    - 规模
    - 足额
    - 配置
    - 专职
    - 安全员
    - 明确
    - 岗位职责
  - id: ③-3
    name: 制定安全教育培训计划，涵盖新工人入场培训、特种作业人员专项培训
    phrases:
    - 制定安全教育培训计划，涵盖新工人入场培训、特种作业人员专项培训
    - 制定安全教育培训计划
    - 涵盖新工人入场培训
    - 特种作业人员专项培训
    terms:
    - 制定
    - 安全
    - 教育
    - 培训
    - 涵盖
    - 工人
    - 入场
    - 特种
    - 作业
    - 人员
    - 专项
  - id: ③-4
    name: 严格执行安全技术交底制度，分部分项工程、关键工序交底
    phrases:
    - 严格执行安全技术交底制度，分部分项工程、关键工序交底
    - 严格执行安全技术交底制度
    - 分部分项工程
    - 关键工序交底
    terms:
    - 严格执行
    - 安全
    - 技术
    - 交底
    - 制度
    - 部分
    - 关键
    - 工序
  - id: ③-5
    name: 建立安全检查制度，包含日常巡查、专项检查、综合检查，形成闭环管理
    phrases:
    - 建立安全检查制度，包含日常巡查、专项检查、综合检查，形成闭环管理
    - 建立安全检查制度
    - 包含日常巡查
    - 专项检查
    - 综合检查
    - 形成闭环管理
    terms:
    - 建立
    - 安全检查
    - 制度
    - 包含
    - 日常
    - 巡查
    - 专项
    - 检查
    - 综合
    - 形成
    - 闭环
  - id: ③-6
    name: 临边洞口防护方案完善，明确楼梯口、电梯井口等防护标准及验收要求
    phrases:
    - 临边洞口防护方案完善，明确楼梯口、电梯井口等防护标准及验收要求
    - 临边洞口防护方案完善
    - 明确楼梯口
    - 电梯井口等防护标准
    - 验收要求
    terms:
    - 临边
    - 洞口
    - 防护
    - 方案
    - 完善
    - 明确
    - 楼梯口
    - 电梯
    - 井口
    - 标准
    - 验收
  - id: ③-7
    name: 临时用电安全符合要求，执行三级配电、两级保护、TN-S接零保护系统
    phrases:
    - 临时用电安全符合要求，执行三级配电、两级保护、TN-S接零保护系统
    - 临时用电安全符合要求
    - 执行三级配电
    - 两级保护
    - TN-S接零保护系统
    terms:
    - 临时
    - 用电
    - 安全
    - 符合要求
    - 执行
    - 三级
    - 配电
    - 两级
    - 保护
    - TN
    - 接零
    - 系统
  phrases:
  - 安全管理体系与措施
  - 安全管理体系
  - 措施
  terms:
  - 安全
  - 管理体系
  - 措施
- mark: ④
  name: 起重机械安全管理规范，执行安装验收、定期检测、操作人员持证上岗制度
  points:
  - id: ④-1
    name: 施工现场消防设施配置齐全，动火作业审批制度严格
    phrases:
    - 施工现场消防设施配置齐全，动火作业审批制度严格
    - 施工现场消防设施配置齐全
    - 动火作业审批制度严格
    terms:
    - 施工现场
    - 消防设施
    - 配置
    - 齐全
    - 动火
    - 作业
    - 审批
    - 制度
    - 严格
  - id: ④-2
    name: 制定坍塌、高处坠落等事故专项应急预案，包含组织机构、救援流程、演练计划
    phrases:
    - 制定坍塌、高处坠落等事故专项应急预案，包含组织机构、救援流程、演练计划
    - 制定坍塌
    - 高处坠落等事故专项应急预案
    - 包含组织机构
    - 救援流程
    - 演练计划
    terms:
    - 制定
    - 坍塌
    - 高处
    - 坠落
    - 事故
    - 专项
    - 应急
    - 预案
    - 包含
    - 组织
    - 机构
    - 救援
    - 流程
    - 演练
  phrases:
  - 起重机械安全管理规范，执行安装验收、定期检测、操作人员持证上岗制度
  - 起重机械安全管理规范
  - 执行安装验收
  - 定期检测
  - 操作人员持证上岗制度
  terms:
  - 起重机械
  - 安全
  - 规范
  - 执行
  - 安装
  - 验收
  - 定期
  - 检测
  - 操作
  - 人员
  - 持证
  - 上岗
  - 制度
- mark: ⑤
  name: 进度管理体系与措施
  points:
  - id: ⑤-1
    name: 建设工程项目管理规范
    phrases:
    - 建设工程项目管理规范
    terms:
    - 建设工程
    - 项目管理
    - 规范
  - id: ⑤-2
    name: 关键线路识别及节点设置合理性
    phrases:
    - 关键线路识别及节点设置合理性
    - 关键线路识别
    - 节点设置合理性
    terms:
    - 关键
    - 线路
    - 识别
    - 节点
    - 设置
    - 合理性
  - id: ⑤-3
    name: 劳动力配置计划表
    phrases:
    - 劳动力配置计划表
    terms:
    - 劳动力
    - 配置
    - 计划表
  - id: ⑤-4
    name: 设备配置清单及维保计划
    phrases:
    - 设备配置清单及维保计划
    - 设备配置清单
    - 维保计划
    terms:
    - 设备
    - 配置
    - 清单
    - 及维保
    - 维保
  - id: ⑤-5
    name: 供应计划表及供应商评估文件
    phrases:
    - 供应计划表及供应商评估文件
    - 供应计划表
    - 供应商评估文件
    terms:
    - 供应
    - 计划表
    - 供应商
    - 评估
    - 文件
  - id: ⑤-6
    name: 赶工预案，针对恶劣天气、设计变更等情况的具体赶工措施
    phrases:
    - 赶工预案，针对恶劣天气、设计变更等情况的具体赶工措施
    - 赶工预案
    - 针对恶劣天气
    - 设计变更等情况的具体赶工措施
    terms:
    - 赶工
    - 预案
    - 针对
    - 恶劣
    - 天气
    - 设计变更
    - 情况
    - 具体
    - 措施
  - id: ⑤-7
    name: 进度动态监测机制、监测流程及调整办法
    phrases:
    - 进度动态监测机制、监测流程及调整办法
    - 进度动态监测机制
    - 监测流程
    - 调整办法
    terms:
    - 进度
    - 动态
    - 监测
    - 机制
    - 流程
    - 调整
    - 办法
  phrases:
  - 进度管理体系与措施
  - 进度管理体系
  - 措施
  terms:
  - 进度
  - 管理体系
  - 措施
- mark: ⑥
  name: 文明施工与环境保护措施
  points:
  - id: ⑥-1
    name: 施工现场围挡及出入口管理
    phrases:
    - 施工现场围挡及出入口管理
    - 施工现场围挡
    - 出入口管理
    terms:
    - 施工现场
    - 围挡
    - 出入口
  - id: ⑥-2
    name: 施工现场容貌管理
    phrases:
    - 施工现场容貌管理
    terms:
    - 施工现场
    - 容貌
  - id: ⑥-3
    name: 施工现场临时设施管理
    phrases:
    - 施工现场临时设施管理
    terms:
    - 施工现场
    - 临时
    - 设施
  - id: ⑥-4
    name: 施工秩序与现场保洁管理
    phrases:
    - 施工秩序与现场保洁管理
    - 施工秩序
    - 现场保洁管理
    terms:
    - 施工
    - 秩序
    - 现场
    - 保洁
  - id: ⑥-5
    name: 施工扬尘控制
    phrases:
    - 施工扬尘控制
    terms:
    - 施工
    - 扬尘
    - 控制
  - id: ⑥-6
    name: 废气排放控制
    phrases:
    - 废气排放控制
    terms:
    - 废气
    - 排放
    - 控制
  - id: ⑥-7
    name: 施工废水处理
    phrases:
    - 施工废水处理
    terms:
    - 施工
    - 废水处理
  - id: ⑥-8
    name: 建筑垃圾处理
    phrases:
    - 建筑垃圾处理
    terms:
    - 建筑
    - 垃圾处理
  - id: ⑥-9
    name: 生活垃圾处理
    phrases:
    - 生活垃圾处理
    terms:
    - 生活
    - 垃圾处理
  - id: ⑥-10
    name: 有害废弃物处理
    phrases:
    - 有害废弃物处理
    terms:
    - 有害
    - 废弃物
    - 处理
  - id: ⑥-11
    name: 施工噪声控制
    phrases:
    - 施工噪声控制
    terms:
    - 施工
    - 噪声控制
  - id: ⑥-12
    name: 污染源头控制
    phrases:
    - 污染源头控制
    terms:
    - 污染源
    - 控制
  - id: ⑥-13
    name: 施工过程防护
    phrases:
    - 施工过程防护
    terms:
    - 施工
    - 过程
    - 防护
  - id: ⑥-14
    name: 施工后土壤修复
    phrases:
    - 施工后土壤修复
    terms:
    - 施工
    - 土壤
    - 修复
  - id: ⑥-15
    name: 植被保护
    phrases:
    - 植被保护
    terms:
    - 植被
    - 保护
  - id: ⑥-16
    name: 水土保持
    phrases:
    - 水土保持
    terms:
    - 水土保持
  - id: ⑥-17
    name: 野生动物保护
    phrases:
    - 野生动物保护
    terms:
    - 野生动物
    - 保护
  phrases:
  - 文明施工与环境保护措施
  - 文明施工
  - 环境保护措施
  terms:
  - 文明
  - 施工
  - 环境保护
  - 措施
- mark: ⑦
  name: 现场组织管理机构
  points:
  - id: ⑦-1
    name: 机构设置完整性与合规性
    phrases:
    - 机构设置完整性与合规性
    - 机构设置完整性
    - 合规性
    terms:
    - 机构
    - 设置
    - 完整性
    - 合规性
  - id: ⑦-2
    name: 核心人员配置
    phrases:
    - 核心人员配置
    terms:
    - 核心
    - 人员
    - 配置
  - id: ⑦-3
    name: 管理制度与流程建设
    phrases:
    - 管理制度与流程建设
    - 管理制度
    - 流程建设
    terms:
    - 管理制度
    - 流程
  - id: ⑦-4
    name: 现场管理保障能力
    phrases:
    - 现场管理保障能力
    terms:
    - 现场
    - 保障
    - 能力
  - id: ⑦-5
    name: 过往业绩与信誉
    phrases:
    - 过往业绩与信誉
    - 过往业绩
    - 信誉
    terms:
    - 过往
    - 业绩
    - 信誉
  - id: ⑦-6
    name: 人员稳定性与培训
    phrases:
    - 人员稳定性与培训
    - 人员稳定性
    - 培训
    terms:
    - 人员
    - 稳定性
    - 培训
  phrases:
  - 现场组织管理机构
  terms:
  - 现场
  - 组织
  - 管理机构
- mark: ⑧
  name: 现场各方协调配合
  points:
  - id: ⑧-1
    name: 内部协调配合
    phrases:
    - 内部协调配合
    terms:
    - 内部
    - 协调
    - 配合
  - id: ⑧-2
    name: 与建设单位协调配合
    phrases:
    - 与建设单位协调配合
    - 建设单位协调配合
    terms:
    - 单位
    - 协调
    - 配合
  - id: ⑧-3
    name: 与监理单位协调配合
    phrases:
    - 与监理单位协调配合
    - 监理单位协调配合
    terms:
    - 监理
    - 单位
    - 协调
    - 配合
  - id: ⑧-4
    name: 与设计/勘察单位协调配合
    phrases:
    - 与设计/勘察单位协调配合
    - 设计/勘察单位协调配合
    terms:
    - 设计
    - 勘察
    - 单位
    - 协调
    - 配合
  - id: ⑧-5
    name: 与行政主管部门协调配合
    phrases:
    - 与行政主管部门协调配合
    - 行政主管部门协调配合
    terms:
    - 行政
    - 主管部门
    - 协调
    - 配合
  - id: ⑧-6
    name: 与周边单位/社区协调配合
    phrases:
    - 与周边单位/社区协调配合
    - 周边单位/社区协调配合
    terms:
    - 周边
    - 单位
    - 社区
    - 协调
    - 配合
  - id: ⑧-7
    name: 协调配合保障措施
    phrases:
    - 协调配合保障措施
    terms:
    - 协调
    - 配合
    - 保障
    - 措施
  phrases:
  - 现场各方协调配合
  terms:
  - 现场
  - 各方
  - 协调
  - 配合
- mark: ⑨
  name: 资源配置计划
  points:
  - id: ⑨-1
    name: 劳动力与进度匹配度
    phrases:
    - 劳动力与进度匹配度
    - 劳动力
    - 进度匹配度
    terms:
    - 劳动力
    - 进度
    - 匹配
  - id: ⑨-2
    name: 设备与工程匹配度
    phrases:
    - 设备与工程匹配度
    - 设备
    - 工程匹配度
    terms:
    - 设备
    - 匹配
  - id: ⑨-3
    name: 供应计划与进度计划衔接性
    phrases:
    - 供应计划与进度计划衔接性
    - 供应计划
    - 进度计划衔接性
    terms:
    - 供应
    - 进度
    - 衔接
  - id: ⑨-4
    name: 资金计划与施工进度匹配度
    phrases:
    - 资金计划与施工进度匹配度
    - 资金计划
    - 施工进度匹配度
    terms:
    - 资金
    - 施工进度
    - 匹配
  phrases:
  - 资源配置计划
  terms:
  - 资源配置
- mark: ⑩
  name: 重难点工程专项施工方案
  points:
  - id: ⑩-1
    name: 深基坑工程方案内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 深基坑工程方案内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 深基坑工程方案内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 深基坑
    - 方案
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-2
    name: 桩基工程方案内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 桩基工程方案内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 桩基工程方案内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 桩基
    - 方案
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-4
    name: 地基处理工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 地基处理工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 地基处理工程内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 地基
    - 处理
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-5
    name: 高支模工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 高支模工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 高支模工程内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 高支模
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-6
    name: 大体积混凝土工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 大体积混凝土工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 大体积混凝土工程内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 体积
    - 混凝土
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-7
    name: 钢结构工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 钢结构工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 钢结构工程内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 钢结构
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-8
    name: 预应力工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 预应力工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 预应力工程内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 预应力
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-9
    name: 高耸与大跨度结构工程类内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 高耸与大跨度结构工程类内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 高耸
    - 大跨度结构工程类内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 高耸
    - 跨度
    - 结构
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-10
    name: 高耸构筑物工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 高耸构筑物工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 高耸构筑物工程内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 高耸
    - 构筑物
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-11
    name: 大跨度空间结构工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 大跨度空间结构工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 大跨度空间结构工程内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 跨度
    - 空间结构
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-12
    name: 城市轨道交通工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 城市轨道交通工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 城市轨道交通工程内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 城市
    - 轨道交通
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  - id: ⑩-13
    name: 桥梁工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    phrases:
    - 桥梁工程内容完整性、施工工艺成熟可靠，技术可行性高，风险可控
    - 桥梁工程内容完整性
    - 施工工艺成熟可靠
    - 技术可行性高
    - 风险可控
    terms:
    - 桥梁工程
    - 完整性
    - 施工工艺
    - 成熟
    - 可靠
    - 技术
    - 可行性
    - 风险
    - 可控
  phrases:
  - 重难点工程专项施工方案
  terms:
  - 重难点
  - 专项
  - 施工
  - 方案
- mark: ⑪
  name: 新技术、新工艺、新材料、新设备应用
  points:
  - id: ⑪-1
    name: 四新技术与项目匹配度
    phrases:
    - 四新技术与项目匹配度
    - 四新技术
    - 项目匹配度
    terms:
    - 四新
    - 技术
    - 匹配
  - id: ⑪-2
    name: 四新技术方案细节完整性
    phrases:
    - 四新技术方案细节完整性
    terms:
    - 四新
    - 技术
    - 方案
    - 细节
    - 完整性
  - id: ⑪-3
    name: 四新技术方案保障措施可行性
    phrases:
    - 四新技术方案保障措施可行性
    terms:
    - 四新
    - 技术
    - 方案
    - 保障
    - 措施
    - 可行性
  - id: ⑪-4
    name: 四新技术效益分析合理性
    phrases:
    - 四新技术效益分析合理性
    terms:
    - 四新
    - 技术
    - 效益
    - 分析
    - 合理性
  - id: ⑪-5
    name: 四新技术类似项目应用案例
    phrases:
    - 四新技术类似项目应用案例
    terms:
    - 四新
    - 技术
    - 类似
    - 应用
    - 案例
  phrases:
  - 新技术、新工艺、新材料、新设备应用
  - 新技术
  - 新工艺
  - 新材料
  - 新设备应用
  terms:
  - 技术
  - 新工艺
  - 材料
  - 设备
  - 应用
