"""核对：招标文件 PDF 的评标办法 vs 拆分评审项.xlsx。

产出 docs/findings-招标文件核对.md 里那张 19 行比对表。
回答一个问题：xlsx 里的评分项、分值、三档区间，是不是招标文件原文。

跨页陷阱：招标文件的评标办法表有单元格跨页续行。原先记为
"p35 末尾断在 1.5-2、分 落在 p36 开头"，2026-08-20 抽 criteria 时看清了
真身：是表格**左列**的项名续行（"时间保证措施；"）插进了**右列**正文的
"1.5-2" 和 "分" 之间，加上一行文档水印 GUID。按页取文本再截窗口，
会把下一项的区间读进来，表现为静默的假不一致——本脚本长期报的
"档位一致 18/19" 就是这么来的，那一项（各专业施工图设计…）实际是一致的。

因此这里不再自己拼页，改为复用 extract_criteria.load_clean_text()：
剔除水印行与左列续行，再把排版断行接回去。两处清洗规则必须是同一份，
否则改了一边另一边会静默漂移。
"""
import collections
import argparse
import json
import os
import re
import sys

import fitz
import openpyxl
import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract_criteria import YAML as PROJECT_YAML  # noqa: E402
from extract_criteria import extract as extract_pdf_criteria  # noqa: E402
from extract_criteria import load_clean_text  # noqa: E402

BASE = "原始资料/实际测试工程文件/济阳区实验高级中学项目工程总承包（EPC） 2"
XLSX = "原始资料/实际测试工程文件/拆分评审项.xlsx"
PAGES = range(32, 38)   # 0-based，技术标评分表所在页 p33~p38
WINDOW = 420            # 从项名往后取多少字里找档位
REFERENCE_JSON = "data/interim/mock/scoring_reference.json"
REFERENCE_JS = "prototype/js/scoring-reference.js"


def tiers(text):
    """取前三个 X-Y分 区间。三档就是一般/良/优。"""
    return re.findall(r"([\d.]+)-([\d.]+)\s*分", text)[:3]


def compact(value):
    return re.sub(r"\s+", "", str(value))


def tier_objects(found):
    return [{"min": float(a), "max": float(b)} for a, b in found]


def sorted_yaml_tiers(item):
    return sorted(
        [{"tier": t["tier"], "min": float(t["min"]), "max": float(t["max"])} for t in item["tiers"]],
        key=lambda t: (t["min"], t["max"]),
    )


def load_inputs():
    base = BASE if os.path.exists(BASE) else BASE.replace("实际测试工程文件", "实际测试文件")
    xlsx = XLSX if os.path.exists(XLSX) else XLSX.replace("实际测试工程文件", "实际测试文件")
    pdf = os.path.join(base, "招标文件.pdf")
    if not os.path.exists(pdf) or not os.path.exists(xlsx):
        sys.exit(f"找不到源文件：{pdf} 或 {xlsx}")
    return pdf, xlsx


def load_xlsx_items(xlsx):
    ws = openpyxl.load_workbook(xlsx, data_only=True)["Sheet1"]
    items = collections.OrderedDict()
    for r in list(ws.iter_rows(values_only=True))[1:]:
        if r[0]:
            items.setdefault(r[0], {
                "guid": str(r[0]),
                "name": str(r[1]),
                "desc": compact(r[2]),
                "desc_raw": str(r[2] or ""),
            })
    return items


def build_reference(pdf, xlsx):
    text, dropped, contam = load_clean_text(pdf)
    raw = compact(text)
    xlsx_items = load_xlsx_items(xlsx)

    yaml_doc = yaml.safe_load(open(PROJECT_YAML, encoding="utf-8"))
    yaml_items = yaml_doc["items"]
    yaml_by_guid = {it["guid"]: it for it in yaml_items}
    pdf_criteria, _, _ = extract_pdf_criteria(yaml_items, pdf=pdf)

    rows = []
    same_cnt = 0
    for guid, xlsx_item in xlsx_items.items():
        name = compact(xlsx_item["name"])
        i = raw.find(name)
        t_pdf = tiers(raw[i:i + WINDOW]) if i >= 0 else []
        t_xls = tiers(xlsx_item["desc"])
        same = len(t_pdf) == 3 and t_pdf == t_xls
        same_cnt += same

        project_item = yaml_by_guid.get(guid)
        rows.append({
            "guid": guid,
            "item_id": project_item["id"] if project_item else "",
            "name": xlsx_item["name"],
            "max_score": project_item["max_score"] if project_item else None,
            "source_page": "招标文件第 33~37 页",
            "pdf_criteria": pdf_criteria.get(project_item["id"], "") if project_item else "",
            "pdf_tiers": tier_objects(t_pdf),
            "xlsx_tiers": tier_objects(t_xls),
            "system_tiers": sorted_yaml_tiers(project_item) if project_item else [],
            "xlsx_desc": xlsx_item["desc_raw"],
            "checks": {
                "pdf_name_found": i >= 0,
                "pdf_vs_xlsx_tiers_match": bool(same),
            },
        })

    return {
        "source_pdf": pdf,
        "source_xlsx": xlsx,
        "generated_by": "scripts/verify_scoring_table.py",
        "pages": "33-37",
        "cleanup": {
            "watermark_lines_dropped": dropped,
            "contaminated_fragments": contam,
        },
        "summary": {
            "items": len(rows),
            "pdf_vs_xlsx_tiers_match": same_cnt,
        },
        "items": rows,
    }


def write_reference(reference, json_out, js_out):
    os.makedirs(os.path.dirname(json_out), exist_ok=True)
    os.makedirs(os.path.dirname(js_out), exist_ok=True)
    with open(json_out, "w", encoding="utf-8") as fh:
        json.dump(reference, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    with open(js_out, "w", encoding="utf-8") as fh:
        fh.write("// Generated by scripts/verify_scoring_table.py. Do not edit by hand.\n")
        fh.write("window.SCORING_REFERENCE = ")
        json.dump(reference, fh, ensure_ascii=False, indent=2)
        fh.write(";\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--write-reference", action="store_true", help="落盘页面②使用的独立核对数据")
    parser.add_argument("--json-out", default=REFERENCE_JSON)
    parser.add_argument("--js-out", default=REFERENCE_JS)
    args = parser.parse_args()

    pdf, xlsx = load_inputs()
    reference = build_reference(pdf, xlsx)
    print(
        f"清洗：剔除水印 {reference['cleanup']['watermark_lines_dropped']} 行、"
        f"左列跨页续行 {len(reference['cleanup']['contaminated_fragments'])} 处 "
        f"{reference['cleanup']['contaminated_fragments']}"
    )

    fmt = lambda t: ";".join(f"{a}-{b}" for a, b in t) or "(未匹配)"
    print(f"{'评分项':<26}{'招标文件档位':<34}{'xlsx档位':<34}一致")
    for row in reference["items"]:
        t_pdf = [(str(t["min"]).rstrip("0").rstrip("."), str(t["max"]).rstrip("0").rstrip(".")) for t in row["pdf_tiers"]]
        t_xls = [(str(t["min"]).rstrip("0").rstrip("."), str(t["max"]).rstrip("0").rstrip(".")) for t in row["xlsx_tiers"]]
        same = row["checks"]["pdf_vs_xlsx_tiers_match"]
        print(f"{compact(row['name'])[:24]:<26}{fmt(t_pdf):<34}{fmt(t_xls):<34}{'✓' if same else '✗'}")

    same_cnt = reference["summary"]["pdf_vs_xlsx_tiers_match"]
    total = reference["summary"]["items"]
    print(f"\n档位一致 {same_cnt}/{total}")
    if args.write_reference:
        write_reference(reference, args.json_out, args.js_out)
        print(f"已写出 {args.json_out}")
        print(f"已写出 {args.js_out}")
    if same_cnt < total:
        print("注：不一致项先按跨页续行人工复核，确认是抽取误差还是真差异。")
    return 0 if same_cnt == total else 1


if __name__ == "__main__":
    sys.exit(main())
